from typing import Protocol

from tom.models.enums import MemoryStatus
from tom.models.event import Event
from tom.models.memory import MemoryItem

from .ledger import RecallResult


class MemoryStore(Protocol):
    async def add_events(self, events: list[Event]) -> None: ...
    async def add_memory_items(self, items: list[MemoryItem]) -> None: ...
    async def list_events(self, session_id: str | None = None) -> list[Event]: ...
    async def list_memory_items(self, session_id: str | None = None) -> list[MemoryItem]: ...
    async def mark_events_processed(self, session_id: str, event_ids: list[str]) -> None: ...
    async def processed_event_ids(self, session_id: str) -> set[str]: ...
    async def get_event(self, event_id: str) -> Event | None: ...
    async def get_memory(self, memory_id: str) -> MemoryItem | None: ...
    async def get_sources(self, memory_id: str) -> list[Event]: ...
    async def list_active_memory(self) -> list[MemoryItem]: ...
    async def update_status(self, memory_id: str, status: MemoryStatus) -> None: ...
    async def recall(self, memory_id: str) -> RecallResult: ...
